_BASE_: "Base-Keypoint-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["stem", "res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["stem", "res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[16], [32], [64], [128], [256], [512]]  # One size for each in feature map
  ROI_HEADS:
    IN_FEATURES: ["p1", "p2", "p3", "p4", "p5"]
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
